all: ws_tracing.py grid.py grid2.py first.py

ws_tracing.py: ws_tracing.ui
	pyuic5 -o ws_tracing.py ws_tracing.ui

grid.py: grid.ui
	pyuic5 -o grid.py grid.ui


grid2.py: grid2.ui
	pyuic5 -o grid2.py grid2.ui

first.py: first.ui
	pyuic5 -o first.py first.ui


